### ISSUE TITLE
Migration error in St Elizabeth Chiga DB IQCarev4 to IQCareV6

### ISSUE THREAD

**Issue by kenochi** [kccb-karp/IQCareMigration#1]
Attached is the error encountered while migrating the database

[MigrationLog.txt](https://github.com/kccb-karp/IQCareMigration/files/2097625/MigrationLog.txt)

**Comment by chris-githu** [comment]
@kenochi 
Please test this in version 1.0.0.15

**Comment by kenochi** [comment]
@chris-githu 
I have run the version 1.0.0.16 and it has sorted the migration error

**Comment by kenochi** [comment]
@chris-githu 
I have run the version 1.0.0.16 and it has sorted the migration error
